# Generated by Django 5.2.7 on 2025-10-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.AddField(
            model_name='students',
            name='studentID',
            field=models.CharField(default='08230116', max_length=20),
            preserve_default=False,
        ),
    ]
